-- 코드를 입력하세요
/*SELECT *
FROM PLACES
WHERE HOST_ID IN
(SELECT HOST_ID FROM PLACES WHERE count(*) >= 2 GROUP BY HOST_ID)*/

SELECT *
FROM PLACES
WHERE HOST_ID IN
      (SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING count(*)>=2);

-- SELECT * FROM PLACES;

-- SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING count(*)>=2;